# Containers - in treefiles
**Treefiles containers allow you to create a directory context in one line of code. You can then use the `treefiles.Tree` interface with file and directories names**.

Containers are automatically loaded/saved. When a container is not empty, filenames are available according to the `Tree` get_attribute protocol.

In [1]:
import treefiles as tf
import os, numpy as np

In [2]:
root = tf.Tree(os.path.curdir)
root

. (/home/gdesrues/Documents/dev/TreeFiles/examples)

In [3]:
root / "some_dir"

'/home/gdesrues/Documents/dev/TreeFiles/examples/some_dir'

In [4]:
with root.ct("first_container", clean=True) as ct:
	print(ct)
	print(ct / "some.file.json")

/home/gdesrues/Documents/dev/TreeFiles/examples/first_container
/home/gdesrues/Documents/dev/TreeFiles/examples/first_container/some.file.json


In [5]:
print(ct)

/home/gdesrues/Documents/dev/TreeFiles/examples/first_container
  └ some.file.json


# Practical usage

In [6]:
arr = np.eye(5)
with root.ct("ct-01") as ct:
	np.save(ct/'arr.npy', arr)

In [7]:
with root.ct("ct-01") as ct:
	arr_copied = np.load(ct.arr)
print(arr_copied)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
with tf.Container(root / "ct-01") as ct:
	arr_copied = np.load(ct.arr)
print(arr_copied)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
